name = "builders-room-bsw"
compatibility_date = "2025-04-20"

# For Cloudflare Pages
pages_build_output_dir = "out"
# Remove build_command from here since we'll run it separately

# Development settings
[dev]
port = 3000
local_protocol = "http"

# D1 Database for registrations
[[d1_databases]]
binding = "DB"
database_name = "builders_room_registrations"
database_id = "c20c8b57-74bb-4462-8f6a-7ce4afd69f60" # This will be replaced with actual ID after creation

# Secret keys can be set using Cloudflare's dashboard or CLI:
# wrangler secret put RESEND_API_KEY
# For email confirmations with Resend.com